### ISSUE TITLE
Cannot run program "git" (in directory "C:\..."): CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by OhadR** [researchgate/gradle-release#155]
I try to run release-plugin using a sample project. my build.gradle looks like:

```
release {
    failOnCommitNeeded = true
    failOnPublishNeeded = true
    failOnSnapshotDependencies = true
    failOnUnversionedFiles = true
    failOnUpdateNeeded = true
    revertOnFail = true
    preCommitText = ''
    preTagCommitMessage = '[Gradle Release Plugin] - pre tag commit: '
    tagCommitMessage = '[Gradle Release Plugin] - creating tag: '
    newVersionCommitMessage = '[Gradle Release Plugin] - new version commit: '
    tagTemplate = '${version}'
/*    versionPropertyFile = 'gradle.properties'
    versionProperties = []
    buildTasks = ['build']
    versionPatterns = [
        /(\d+)([^\d]*$)/: { Matcher m, Project p -> m.replaceAll("${(m[0][1] as int) + 1}${m[0][2]}") }
    ]
    scmAdapters = [
        net.researchgate.release.GitAdapter,
        net.researchgate.release.SvnAdapter,
        net.researchgate.release.HgAdapter,
        net.researchgate.release.BzrAdapter
    ]*/

    svn {
        username = null
        password = null
    }
}
```

(and of course the plugin itself in the beginning of the file)

when i run >gradle release, I get this error:

```
:release FAILED
Release process failed, reverting back any changes made by Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify task execution listener.
> Cannot run program "git" (in directory "C:\...\gradle-release-plugin-test"): CreateProcess error=2, The system cannot find the file specified

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify task execution listener.
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:55)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
....
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.io.IOException: Cannot run program "git" (in directory "C:\Ohad\Dev\Projects\gradle-release-plugin-test"): CreateProcess err
or=2, The system cannot find the file specified
        at net.researchgate.release.cli.Executor.exec(Executor.groovy:35)
        at net.researchgate.release.cli.Executor$exec.call(Unknown Source)
        at net.researchgate.release.PluginHelper.exec(PluginHelper.groovy:61)
        at net.researchgate.release.PluginHelper$exec$2.callCurrent(Unknown Source)
        at net.researchgate.release.GitAdapter.revert(GitAdapter.groovy:131)
        at net.researchgate.release.GitAdapter$revert$2.call(Unknown Source)
        at net.researchgate.release.ReleasePlugin$_apply_closure6.doCall(ReleasePlugin.groovy:132)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        ... 53 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        ... 63 more
```

why is it searching for "git"?

**Comment by danez** [comment]
The release plugin needs the git cli, as stated in the README. Make sure to have git installed and working in your environment.

**Comment by OhadR** [comment]
but i do not work with GIT, I work with SVN. the README states that SVN is also supported...

**Comment by stevelooo** [comment]
The project has JGit as the dependency. Since JGit v4, it tries to find the Git System Configuration. It will try to find the git.exe or git.bash from the PATH. If it doesn't find, it will try to run "bash.exe" to find the git. Your machine has installed the bash program.

So when doing the command "bash --login -c which git", your machine doesn't return empty. Therefore, JGit library thought your machine has git installed. However, your machine doesn't. So when JGit library runs "git" command, it throws errors.

reference
http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.jgit/org.eclipse.jgit/4.0.1.201506240215-r/org/eclipse/jgit/util/FS.java#FS.discoverGitExe%28%29
