### ISSUE TITLE
Gradle 9.0: The StartParameter.settingsFile property has been deprecated.

### ISSUE THREAD

**Issue by IRus** [researchgate/gradle-release#379]
The StartParameter.settingsFile property has been deprecated.	
This is scheduled to be removed in Gradle 9.0.	
Please use 'projectDir' to specify the directory of the default project instead.	
[Documentation](https://docs.gradle.org/8.1/userguide/upgrading_version_8.html#configuring_custom_build_layout)	
1 usage	
Plugin:net.researchgate.release

	at org.gradle.StartParameter.logBuildOrSettingsFileDeprecation(StartParameter.java:504)	
		•••
	at net.researchgate.release.ReleasePlugin$_apply_closure5.doCall(ReleasePlugin.groovy:107)	
		•••
	at net.researchgate.release.ReleasePlugin.apply(ReleasePlugin.groovy:100)	
	at net.researchgate.release.ReleasePlugin.apply(ReleasePlugin.groovy)	
		•••

**Comment by Vampire** [comment]
Would probably also be fixed by fixing #304

**Comment by pgehl** [comment]
Gradle 9.0 is coming fast. And no code commit listed in the last 2 years. Is this project still alive ?

**Comment by patton73** [comment]
Honestly i cannot understand why people start projects and the suddenly abandon them. I hope this project is not dead. But no commits in 2 years is a really bad signal.

**Comment by windmueller** [comment]
> Honestly i cannot understand why people start projects and the suddenly abandon them.

You can't seriously imagine that personal circumstances could change in such a way that one can no longer find the time for a project that one would like to take?

But perhaps the author no longer uses Gradle so there could be a huge drop regarding motivation.

However, this is all speculation and has nothing to do with the problem at hand. Perhaps it is time for an "official" fork.

**Comment by pgehl** [comment]
My apologies to the author . My question was not ment in an offensive way. 
I'm honestly grateful for this plugin and all the years I used it free of charge.
I asked only if the project was still alive to be able to plan a transition for the tens of projects that use it.
Again, thanks the author(s) for all those years.

**Comment by patton73** [comment]
> You can't seriously imagine that personal circumstances could change in such a way that one can no longer find the time for a project that one would like to take?

Well sure i can imagine because real life could always be very complicated. But when this happens then you can always try to find someone else who can continue the work. The community is usually big and people are awesome in helping. 
Asking for help does not cost too much.

**Comment by patton73** [comment]
>  I asked only if the project was still alive to be able to plan a transition for the tens of projects that use it. 

Ehm excuse me. Plan a transition to what exactly? Is there a similar plugin? 
Thanks for any information you can provide.

**Comment by Doc94** [comment]
maybe im confuse but this cannot help or is totally different task?
https://docs.gradle.org/current/userguide/publishing_maven.html

**Comment by Vampire** [comment]
Totally different, yes. :-)

**Comment by IRus** [comment]
If the fix for this particular issue is just removing one line?

https://github.com/researchgate/gradle-release/blob/main/src/main/groovy/net/researchgate/release/ReleasePlugin.groovy#L107

Or this change would break some older Gradle versions?

**Comment by Vampire** [comment]
> If the fix for this particular issue is just removing one line?

There are other problems, and as I said above, the best would be to solve #304 which would also fix this one alongside.

**Comment by IRus** [comment]
@Vampire yes, I agree, but it appears that this is a minor fix that can be done before #304

@Hillkorn any chance giving commit rights to @Vampire? I can help with testing. Gradle seems not pushing 9.0 soon, there is 8.8-8.10 in queue, but composite builds requested by the community, and we could work on fixing this, as well as merging PR queue.

**Comment by patton73** [comment]
This bug is not fixed in version 3.1.0

Gradle still complains about StartParameter.settingsFile property deprecation.

`The StartParameter.settingsFile property has been deprecated. This is scheduled to be removed in Gradle 9.0. Setting custom build file to select the default project has been deprecated. Please use 'projectDir' to specify the directory of the default project instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#configuring_custom_build_layout`

**Comment by IRus** [comment]
@patton73 it's will not be used in Gradle 9.0, because special condition added

**Comment by Vampire** [comment]
Besides that it will silently behave differently instead.
Would probably have been better if you checked whether it is the default file and throw an error if not.
